### PR TITLE
pt-rBR translation

### PR DESCRIPTION
**Pull request by iraamaro**
Inserted translation.

### CODE REVIEW

**Comment by pzmarzly** [comment]
Thanks a lot for this.

@medape should debug messages (`log_`) be translated?

**Comment by medape** [comment]
@iramaro This is great, thank you!

@pzmarzly I don't know, is there an accepted practice or a de facto standard? If not, translating them seems much more convenient for users, developers can always find a way to deal with other users' logcats.

**Comment by pzmarzly** [comment]
@medape Are these debug strings presented inside the app? If so, then they should be translated. If not, then it differs from app to an app, and I don't have an opinion about that.

**Comment by medape** [comment]
@pzmarzly Debug strings (`log_`) are only ever output to the logcat.

On the other hand, strings whose ID begins with `error_` are both shown within the app and sent to the logcat, so I suppose translating everything would be more consistent.

**Comment by pzmarzly** [comment]
OK, merging...

**Pull request merged**
