### PR TITLE
Removing extra weight from the Android app

### PR DESCRIPTION
**Pull request by medape**
Theses commits should delete unused content from the app, and send to `events.py` ONLY the argument of `Yoke.update_vals()`, with no other change in behaviour.

Please review the code and test. It worked for me, but I've never wrote an Android application from scratch and I can do little else than removing bits of code.

Also change your version number to whatever system you prefer, I just put a tentative number to better tell apart this version from [`rmst/yoke/devel/app-debug.apk`](https://github.com/rmst/yoke/blob/master/devel/app-debug.apk)

### CODE REVIEW

**Comment by pzmarzly** [comment]
This completely broke zeroconf discovery due to removal of `onResume`. Keep in mind that [it is also called on the first launch](https://stackoverflow.com/a/15658753/5108318).

**Comment by pzmarzly** [comment]
Also, looking at https://github.com/rmst/yoke/pull/36, I think keep-alive message every 500 or 1000 ms wouldn't hurt too much.

**Comment by medape** [comment]
Okay, there is some work to do. I'll start by trying to fix the APK. The keep-alive message can be sent from the webpage.

Also, I need to move code from `base.js` to Python. Sending a long string with kernel events results in this being cut off after the 128th or 129th characters (due to the buffer limit), and `service.py` discarding the layout. So I think I'll send a string with the short aliases instead (`j1`, `b1`...), it seems the more sensible option.

**Comment by medape** [comment]
APK released. I still need to edit `service.py` so it won't get destroy and create devices on a loop. (Right now the APK sends continously the layout until I press a button.)

EDIT: Every bug listed on this PR is now fixed, please check again.

**Comment by pzmarzly** [comment]
This was merged in `rmst/yoke`, @rmst please merge.

**Comment by rmst** [comment]
Hi, sorry it took me so long! @pzmarzly I gave you write permission here, now. I see this removes the native Android motion sensor movement. I assume this functionality has been adequately moved to the javascript part?

**Comment by pzmarzly** [comment]
> I assume this functionality has been adequately moved to the javascript part?

Yup. Binary build of this PR was already merged to `rmst/yoke` (`app-devel.apk`)

**Pull request merged**
