### PR TITLE
Grand bug fix festival, still incomplete

### PR DESCRIPTION
**Pull request by medape**
This is still the very first Android app I'm working on, and half my work is based on StackOverflow's answer and copy-pasting from @rmst. I'm hoping I don't forget to document anything here.

- Yoke is now fully fullscreen. Issue #4 (hiding the navigation bar) is now fixed.
- Two nice things from [issue 33 on `rmst/yoke`](https://github.com/rmst/yoke/issues/33) are implemented:
  - refresh button, with an icon downloaded from https://material.io/resources/icons/
  - app now forgets the joypad state upon disconnection. It won't send the latest status anymore.
- Moved every string (even debug messages) to `values/strings.xml`, to allow easy localisation in the future. I had to create very long strings and it was becoming too much.
- Done some preliminary work on applying a uniform style to the app, but buttons are still ugly as sin.
- Improved the manifest file.
- We were right about file:// being a secure origin: the WebView now reads from the external storage, restoring motion controls and fixing [issue 39 from `rmst/yoke`](https://github.com/rmst/yoke/issues/39) .
- Added greeter screen.

Most work is needed on these two last points. The greeter screen is a separate Activity with a very simple layout welcoming the user and guiding them around errors. If it detects a layout already in your phone, it automatically skips to the real app.

It's also supposed to allow the user to copy a default layout with the click of a button, but I haven't added the code for that yet.

Special permissions are needed to write to `Android/data/com.simonramstedt/files` in the external storage, but not to read it. The current code doesn't include this permission yet.

I suppose the easiest way would be to bundle our layout in the APK, and ask the user to grant `WRITE_STORAGE_PERMISSION`, and then copy to it. Anyways, @rmst, @pzmarzly, I'd like your opinions on this. (I'd also like you to check these commits for bugs or things to improve.) I'll upload the binary for this version on Releases.

There's no need to update the `yoke` repo to merge this PR.

### CODE REVIEW

**Comment by pzmarzly** [comment]
Thanks again for continuing to dedicate your time for Yoke.

> This is still the very first Android app I'm working on, and half my work is based on StackOverflow's answer

I wouldn't known this if you didn't tell us. The changes look good to me. And 50% copy-and-paste is still a low number for software project :wink:

> Special permissions are needed to write to Android/data/com.simonramstedt/files in the external storage, but not to read it. The current code doesn't include this permission yet.

That's weird. Could you try using [`getFilesDir()`](https://developer.android.com/reference/android/content/Context.html#getFilesDir()) and [`openFileOutput()`](https://developer.android.com/reference/android/content/Context.html#openFileOutput(java.lang.String,%20int)) instead of `getExternalFilesDir()`?

**Comment by medape** [comment]
> Thanks again for continuing to dedicate your time for Yoke.

No need to thank me, I want to use this just as anyone here wants to. ;)

> That's weird. Could you try using [`getFilesDir()`](https://developer.android.com/reference/android/content/Context.html#getFilesDir()) and [`openFileOutput()`](https://developer.android.com/reference/android/content/Context.html#openFileOutput(java.lang.String,%20int)) instead of `getExternalFilesDir()`?

I tried just now. The file is correctly created, but it's written to `/data/user/0/com.simonramstedt.yoke/files` instead, a directory I can only see from the recovery. Your typical user can't read this folder, even through ADB.

We really need that permission after all.

**Comment by pzmarzly** [comment]
Back when I proposed local storage (`file://`) as a solution to the secure origin error, I didn't mean to suggest removing Python HTTP server altogether. I was thinking about the app downloading files from PC to the local storage, and then opening them via `file://`. I still think that configuring the app via PC is the most comfortable solution. But if you don't, then maybe we could indeed add this permission (or use [SAF](https://developer.android.com/guide/topics/providers/document-provider) for [folder selection](https://stackoverflow.com/a/22561096/5108318)).

**Comment by medape** [comment]
My bad, I misunderstood you then.

Were you planning on downloading the files on every connection, then loading them from internal storage? That looks like a very obvious way to bypass the Secure Origins Policy... and if we are to abide to that, I'd rather make it somewhat less obvious and add some extra functions, like this one:

> [...] It's also the only way each user can customize separately their gamepads. (With the current system, configuration is per computer, and every user is forced to use the same base code and layouts.)

Still, you're right in that copy pasting through MTP, and selecting the correct folder is annoying, and internal storage doesn't require extra permissions. That's something to think about.

What do you think about downloading the files to internal storage **just the first time**, and then having an update button within the app?

When the user truly wants to update the layout in their phone, they could just connect to their machine, tap a menu button (⋮) in the action bar, and tap an option like “Update layouts”. Tapping two buttons is still quick and easy, and this way, users won't need to use different layouts if they ever connect to a different machine, o risk malicious code.

(I don't know how SAF would work, but we probably wouldn't need it if we follow this approach.)

**Comment by pzmarzly** [comment]
> What do you think about downloading the files to internal storage just the first time, and then having an update button within the app?

That sounds okay. A bit weird, but I guess it would have its fans.

> risk malicious code

I don't think there's much that HTML, JS and `Yoke.update_vals` can do in terms of malicious behavior. Perhaps it could fill all free phone's storage, but Android is still usable when this happens.

> I don't know how SAF would work, but we probably wouldn't need it if we follow this approach

It would indeed be irrelevant. SAF is just an alternative for the Storage permission (SAF lets user give app permission for one folder/one file instead of all `/data/media/0`).

**Comment by medape** [comment]
Then I'll work on it.

Sorry for my recent inactivity. I've been lately more busy with work and studies. I'd still love to see this app complete, and I will keep sending commits and such, but a much slower pace.

I suppose this is no surprise for you, but I'd rather tell you directly and assure you I haven't forgotten about this. :relaxed:

**Comment by medape** [comment]
**Edited because I accidentally some words.**

Please forgive me if my latest commits are a bit of a mess, I've been running into some weird and exciting errors... and I've been constantly renaming and recategorising the strings.

I've tested this for a short while and everything should be working now. Basically:

A progress bar, and a new button.
-----

I've added a narrow, screen-wide progress bar between the top bar and the webview. It could use some new polish, but it works well.

There's also a new button that spawns a floating menu when clicked. For the moment, the menu just has one action ("Upgrade gamepad") but I suspect that's going to change soon. :wink: 

The top bar is still ugly and it would be interesting to convert it to [a proper `ActionBar`](https://developer.android.com/training/appbar).

Download once and forget
-----

I've implemented the mechanism I insisted on. Updating the layout and connecting to a webserver are completely independent. If the user has never downloaded a layout in this version, or if they try to download a layout before connecting to a webserver, the app warns them with a toast.

As I said on [`rmst/yoke`'s pull request](https://github.com/rmst/yoke/pull/41), the first thing this app downloads from a webserver is a JSON file with no file extension (maybe I should have added one), called `manifest`. It reads this file, then creates the necessary folders, then downloads every file listed in manifest sequentially. (I took care of preventing `manifest` from listing itself.)

There's also a failsafe. New gamepads are downloaded to the folder `future`, and only if the download is succesfull, the working gamepad is deleted and the folder `future` is renamed to become the new working gamepad.

Improved error handling
-----

The application now complains of more things, categorises its messages into "debug" and "error", and issues an `AlertDialog` for every error. I tried to write user-friendly strings for the most-common errors (or at least the ones I'm positive of the cause).

It also immediately disconnects from the webserver if an exception is raised from `send()`. This should only happen if:
- we attempt to send a `null` value, or
- the connection is refused (typically because the Yoke webserver was stopped or broke).

New global variables
-----

Yoke now saves the address and port of its current connection in global variables `currentHost` and `currentPort`.

This makes the code base sligthly more insane and may bring some side effects if not careful, but it was the only way I could think of to allow upgrading the gamepad upgrades at any time.

**Comment by pzmarzly** [comment]
I think it would be nice if `DownloadFilesFromURL` class was moved into a separate file. I'm not an Android developer, but I heard some of them complaining that their `*Activity.java` files are 1000s of lines long, and that it's hard to avoid that due to how Android Java API is built (verbose, boilerplate-y, callback-based, centralized around `Activity`). It looks to me like you've already done some work to separate download-in-background stuff from the rest, so we could avoid that problem.

This is just a thought, though. You don't have to do it (especially if it requires non-trivial effort).

**Comment by medape** [comment]
`DownloadFilesFromURL` was on a separate file on my first experiments, but I was having some problems with compiling that. Something about creating explicitly handlers, references to Activity and Context, besides adding the boilerplate code for a new Java file.

So I'm not too keen on trying it again - this way is shorter, and I don't expect the class to keep growing. Some lines of code could certainly use some cleanup (especially the one notifying success on downloading) but I think I'll do some experiments for my PR, after I add more functionality or fix more user-facing errors.

With that aside, is there anything you would improve on this PR?

**Comment by pzmarzly** [comment]
> So I'm not too keen on trying it again

No problem.

> is there anything you would improve on this PR?

Maybe renaming `manifest` to `manifest.json`, like you've suggested before? Nothing else comes to my mind, and this PR has grown pretty large already, so it would be nice to have it merged.

**Comment by medape** [comment]
That's all for now, then.

You can merge now. Please remember to merge my PR at `rmst/yoke`, close [issue `yoke`#39](https://github.com/rmst/yoke/issues/39) there, and update the checklist at [issue `yoke`#33](https://github.com/rmst/yoke/issues/33).

EDIT: Please close [issue `yoke`#13](https://github.com/rmst/yoke/issues/13) too - Yoke was tested in Windows 10 and should work in any Windows from 7 to 10, with 32- or 64-bit Python modules.

**Pull request merged**
